---
# tasks file for gunicorn
- name: Creating and opening systemd socket file for gunicorn
  copy:
    src: gunicorn.socket
    dest: /etc/systemd/system/gunicorn.socket
    owner: root
    group: root
    mode: 0644

- name: Creating and opening systemd service file for gunicorn
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    owner: root
    group: root
    mode: 0644
  notify: start gunicorn socket and service