---

- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    state: present
  tags: packages

- name: Configure Nginx to Proxy Pass to Gunicorn
  template:
    src: '{{ application_name }}.j2'
    dest: /etc/nginx/sites-available/{{ application_name }}
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: Ensure that the application site is enabled
  file: 
    src: /etc/nginx/sites-available/{{ application_name }}
    dest: /etc/nginx/sites-enabled/{{ application_name }}
    state: link
  notify: reload nginx

- name: Start nginx service
  service:
    name: nginx
    state: started
    enabled: true
  notify: restart nginx service